# Generated by Django 5.0.4 on 2024-05-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='applicationMethod',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='context',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='eligibillty',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='img',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='link',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='startDate',
        ),
    ]
