# Generated by Django 5.0.4 on 2024-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_remove_comp_applicationmethod_remove_comp_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='applicationMethod',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='contact',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='eligibillty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='link',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='organization',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='reward',
            field=models.TextField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
