# Generated by Django 5.0.4 on 2024-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_comp_applicationmethod_comp_contact_comp_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='endDate',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='startDate',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
