# Generated by Django 5.0.4 on 2024-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_alter_comp_enddate_alter_comp_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='contact',
            field=models.TextField(null=True),
        ),
    ]
