# Generated by Django 5.0.4 on 2024-05-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("nickname", models.CharField(default="Anonymous", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("tier", models.CharField(max_length=50, null=True)),
                ("userIntro", models.CharField(max_length=500, null=True)),
                ("skill", models.CharField(max_length=500, null=True)),
                ("experience", models.CharField(max_length=500, null=True)),
                ("githubLink", models.CharField(max_length=100, null=True)),
                ("snsLink", models.CharField(max_length=200, null=True)),
                ("city", models.CharField(max_length=20, null=True)),
                ("dong", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="user.basicuser",
                    ),
                ),
            ],
        ),
    ]
