# Generated by Django 5.0.4 on 2024-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicuser",
            name="nickname",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
    ]
